In [1]:
import numpy as np

## Data Types and Attributes

In [2]:
# NumPy's main datatype is ndarray

# Vector 1D
array1 = np.array([1,2,3,4,5])
array1

array([1, 2, 3, 4, 5])

In [3]:
type(array1)

numpy.ndarray

In [4]:
# Matrix 2D or 3D
array2 = np.array([[1,2,3],[4,5,6],[1.1,2.2,3.3]])
array2

array([[1. , 2. , 3. ],
       [4. , 5. , 6. ],
       [1.1, 2.2, 3.3]])

In [5]:
array3 = np.array([[[1,2.4,3.5,4],[4,5,10,9.9],[10,20,30,40]],
                   [[1,2,3,7],[1.1,2.2,3.3,4.4],[1,2.3,4,5]]])
array3

array([[[ 1. ,  2.4,  3.5,  4. ],
        [ 4. ,  5. , 10. ,  9.9],
        [10. , 20. , 30. , 40. ]],

       [[ 1. ,  2. ,  3. ,  7. ],
        [ 1.1,  2.2,  3.3,  4.4],
        [ 1. ,  2.3,  4. ,  5. ]]])

In [6]:
array1.shape

(5,)

In [7]:
array2.shape

(3, 3)

In [8]:
array3.shape

(2, 3, 4)

In [9]:
# Number of dimensions
array1.ndim, array2.ndim, array3.ndim

(1, 2, 3)

In [10]:
array1.dtype, array2.dtype, array3.dtype

(dtype('int32'), dtype('float64'), dtype('float64'))

In [11]:
# Number of elements in array
array1.size, array2.size, array3.size

(5, 9, 24)

In [12]:
# Create a DataFrame from a NumPy array
import pandas as pd

df = pd.DataFrame(array2)
df

0    1    2
0  1.0  2.0  3.0
1  4.0  5.0  6.0
2  1.1  2.2  3.3

## Creating NumPy arrays

In [13]:
sample_array = np.array([1, 2, 3])
sample_array

array([1, 2, 3])

In [14]:
sample_array.dtype

dtype('int32')

In [15]:
# Return array filled with ones
ones = np.ones((2, 3))
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [16]:
ones.dtype

dtype('float64')

In [17]:
type(ones)

numpy.ndarray

In [18]:
# Return array filled with zeroes
zeroes = np.zeros((3, 3))
zeroes

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [19]:
# Retrun array with a range
range_array = np.arange(0, 10, 2)
range_array

array([0, 2, 4, 6, 8])

In [20]:
# Return array with random integer values
random_array = np.random.randint(0, 10, size = (3, 5))
random_array

array([[5, 4, 2, 7, 0],
       [4, 1, 4, 0, 3],
       [6, 7, 5, 5, 7]])

In [21]:
random_array.size

15

In [22]:
random_array.shape

(3, 5)

In [23]:
# Return random floats in half open interval in an array
random_array2 = np.random.random((5, 3))
random_array2

array([[0.03888598, 0.00829562, 0.43333441],
       [0.21684137, 0.67364032, 0.22842095],
       [0.61364724, 0.62919366, 0.97701598],
       [0.86396136, 0.02869634, 0.06030714],
       [0.90942812, 0.93579314, 0.50983562]])

In [24]:
random_array2.shape

(5, 3)

In [25]:
# Return values in a given shape with random values
random_array3 = np.random.rand(5,3)
random_array3

array([[0.62616625, 0.36866881, 0.76788053],
       [0.20207524, 0.28204157, 0.4938139 ],
       [0.3099982 , 0.76270332, 0.96669122],
       [0.34179714, 0.88842037, 0.1766057 ],
       [0.52048651, 0.55332174, 0.04825597]])

In [26]:
# Pseudo-random numbers
# Generate same random numbers not changing every run of cell
np.random.seed(seed=0)
random_array4 = np.random.randint(10, size=(5,3))
random_array4

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2],
       [4, 7, 6],
       [8, 8, 1]])

In [27]:
random_array4.shape

(5, 3)

In [28]:
np.random.seed(7)
random_array5 = np.random.random((5,3))
random_array5

array([[0.07630829, 0.77991879, 0.43840923],
       [0.72346518, 0.97798951, 0.53849587],
       [0.50112046, 0.07205113, 0.26843898],
       [0.4998825 , 0.67923   , 0.80373904],
       [0.38094113, 0.06593635, 0.2881456 ]])

In [29]:
random_array5 = np.random.random((5,3))
random_array5

array([[0.90959353, 0.21338535, 0.45212396],
       [0.93120602, 0.02489923, 0.60054892],
       [0.9501295 , 0.23030288, 0.54848992],
       [0.90912837, 0.13316945, 0.52341258],
       [0.75040986, 0.66901324, 0.46775286]])

## Viewing Arrays and Matrices

In [30]:
# Find unique values in an array
np.unique([1,1,1,2,2,3,3,3])

array([1, 2, 3])

In [31]:
np.unique(random_array4)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [45]:
array3

array([[[ 1. ,  2.4,  3.5,  4. ],
        [ 4. ,  5. , 10. ,  9.9],
        [10. , 20. , 30. , 40. ]],

       [[ 1. ,  2. ,  3. ,  7. ],
        [ 1.1,  2.2,  3.3,  4.4],
        [ 1. ,  2.3,  4. ,  5. ]]])

In [46]:
array3.shape

(2, 3, 4)

In [47]:
array3[:2, :2, :2]

array([[[1. , 2.4],
        [4. , 5. ]],

       [[1. , 2. ],
        [1.1, 2.2]]])

In [48]:
# Last number in the size parameter are the number of values in array 
# then continue going outwards for the number of arrays.
# 5 values, 4 arrays inside 3 arrays inside 2 arrays
array4 = np.random.randint(10, size=(2,3,4,5))
array4

array([[[[6, 7, 7, 9, 3],
         [0, 7, 7, 7, 0],
         [5, 4, 3, 1, 3],
         [1, 3, 4, 3, 1]],

        [[9, 5, 9, 1, 2],
         [3, 2, 2, 5, 7],
         [3, 0, 9, 9, 3],
         [4, 5, 3, 0, 4]],

        [[8, 6, 7, 2, 7],
         [3, 8, 6, 6, 5],
         [6, 5, 7, 1, 5],
         [4, 4, 9, 9, 0]]],


       [[[6, 2, 6, 8, 2],
         [4, 1, 6, 1, 5],
         [1, 6, 9, 8, 6],
         [5, 9, 7, 5, 4]],

        [[9, 6, 8, 1, 5],
         [5, 8, 3, 7, 7],
         [9, 4, 7, 5, 9],
         [6, 2, 0, 5, 3]],

        [[0, 5, 7, 1, 8],
         [4, 9, 0, 2, 0],
         [7, 6, 2, 9, 9],
         [5, 1, 0, 0, 9]]]])

In [49]:
array4.shape

(2, 3, 4, 5)

In [50]:
array4[0]

array([[[6, 7, 7, 9, 3],
        [0, 7, 7, 7, 0],
        [5, 4, 3, 1, 3],
        [1, 3, 4, 3, 1]],

       [[9, 5, 9, 1, 2],
        [3, 2, 2, 5, 7],
        [3, 0, 9, 9, 3],
        [4, 5, 3, 0, 4]],

       [[8, 6, 7, 2, 7],
        [3, 8, 6, 6, 5],
        [6, 5, 7, 1, 5],
        [4, 4, 9, 9, 0]]])

In [54]:
# Get the first 4 numbers of innermost arrays
array4[:,:,:,:4]

array([[[[6, 7, 7, 9],
         [0, 7, 7, 7],
         [5, 4, 3, 1],
         [1, 3, 4, 3]],

        [[9, 5, 9, 1],
         [3, 2, 2, 5],
         [3, 0, 9, 9],
         [4, 5, 3, 0]],

        [[8, 6, 7, 2],
         [3, 8, 6, 6],
         [6, 5, 7, 1],
         [4, 4, 9, 9]]],


       [[[6, 2, 6, 8],
         [4, 1, 6, 1],
         [1, 6, 9, 8],
         [5, 9, 7, 5]],

        [[9, 6, 8, 1],
         [5, 8, 3, 7],
         [9, 4, 7, 5],
         [6, 2, 0, 5]],

        [[0, 5, 7, 1],
         [4, 9, 0, 2],
         [7, 6, 2, 9],
         [5, 1, 0, 0]]]])

## Manipulating and Comparing Arrays

### Arithmetic 

In [61]:
a1 = np.array([1,2,3])
a1

array([1, 2, 3])

In [59]:
ones = np.ones(3)
ones

array([1., 1., 1.])

In [63]:
a1 + ones

array([2., 3., 4.])

In [64]:
a1 - ones

array([0., 1., 2.])

In [65]:
a1 * ones

array([1., 2., 3.])

In [67]:
array2 * a1

array([[ 1. ,  4. ,  9. ],
       [ 4. , 10. , 18. ],
       [ 1.1,  4.4,  9.9]])