In [2]:
import numpy as np

## Data Types and Attributes

In [3]:
# NumPy's main datatype is ndarray

# Vector 1D
array1 = np.array([1,2,3,4,5])
array1

array([1, 2, 3, 4, 5])

In [4]:
type(array1)

numpy.ndarray

In [5]:
# Matrix 2D or 3D
array2 = np.array([[1,2,3],[4,5,6],[1.1,2.2,3.3]])
array2

array([[1. , 2. , 3. ],
       [4. , 5. , 6. ],
       [1.1, 2.2, 3.3]])

In [12]:
array3 = np.array([[[1,2.4,3.5,4],[4,5,10,9.9],[10,20,30,40]],
                   [[1,2,3,7],[1.1,2.2,3.3,4.4],[1,2.3,4,5]]])
array3

array([[[ 1. ,  2.4,  3.5,  4. ],
        [ 4. ,  5. , 10. ,  9.9],
        [10. , 20. , 30. , 40. ]],

       [[ 1. ,  2. ,  3. ,  7. ],
        [ 1.1,  2.2,  3.3,  4.4],
        [ 1. ,  2.3,  4. ,  5. ]]])

In [13]:
array1.shape

(5,)

In [14]:
array2.shape

(3, 3)

In [15]:
array3.shape

(2, 3, 4)

In [16]:
# Number of dimensions
array1.ndim, array2.ndim, array3.ndim

(1, 2, 3)

In [17]:
array1.dtype, array2.dtype, array3.dtype

(dtype('int32'), dtype('float64'), dtype('float64'))

In [18]:
# Number of elements in array
array1.size, array2.size, array3.size

(5, 9, 24)

In [21]:
# Create a DataFrame from a NumPy array
import pandas as pd

df = pd.DataFrame(array2)
df

0    1    2
0  1.0  2.0  3.0
1  4.0  5.0  6.0
2  1.1  2.2  3.3