In [2]:
import numpy as np

## Data Types and Attributes

In [3]:
# NumPy's main datatype is ndarray

# Vector 1D
array1 = np.array([1,2,3,4,5])
array1

array([1, 2, 3, 4, 5])

In [4]:
type(array1)

numpy.ndarray

In [5]:
# Matrix 2D or 3D
array2 = np.array([[1,2,3],[4,5,6],[1.1,2.2,3.3]])
array2

array([[1. , 2. , 3. ],
       [4. , 5. , 6. ],
       [1.1, 2.2, 3.3]])

In [6]:
array3 = np.array([[[1,2.4,3.5,4],[4,5,10,9.9],[10,20,30,40]],
                   [[1,2,3,7],[1.1,2.2,3.3,4.4],[1,2.3,4,5]]])
array3

array([[[ 1. ,  2.4,  3.5,  4. ],
        [ 4. ,  5. , 10. ,  9.9],
        [10. , 20. , 30. , 40. ]],

       [[ 1. ,  2. ,  3. ,  7. ],
        [ 1.1,  2.2,  3.3,  4.4],
        [ 1. ,  2.3,  4. ,  5. ]]])

In [7]:
array1.shape

(5,)

In [8]:
array2.shape

(3, 3)

In [9]:
array3.shape

(2, 3, 4)

In [10]:
# Number of dimensions
array1.ndim, array2.ndim, array3.ndim

(1, 2, 3)

In [11]:
array1.dtype, array2.dtype, array3.dtype

(dtype('int32'), dtype('float64'), dtype('float64'))

In [12]:
# Number of elements in array
array1.size, array2.size, array3.size

(5, 9, 24)

In [13]:
# Create a DataFrame from a NumPy array
import pandas as pd

df = pd.DataFrame(array2)
df

0    1    2
0  1.0  2.0  3.0
1  4.0  5.0  6.0
2  1.1  2.2  3.3

## Creating NumPy arrays

In [14]:
sample_array = np.array([1, 2, 3])
sample_array

array([1, 2, 3])

In [15]:
sample_array.dtype

dtype('int32')

In [18]:
# Return array filled with ones
ones = np.ones((2, 3))
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [19]:
ones.dtype

dtype('float64')

In [20]:
type(ones)

numpy.ndarray

In [21]:
# Return array filled with zeroes
zeroes = np.zeros((3, 3))
zeroes

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [22]:
# Retrun array with a range
range_array = np.arange(0, 10, 2)
range_array

array([0, 2, 4, 6, 8])

In [25]:
# Return array with random integer values
random_array = np.random.randint(0, 10, size = (3, 5))
random_array

array([[0, 5, 9, 1, 2],
       [7, 8, 9, 4, 9],
       [0, 8, 5, 9, 9]])

In [26]:
random_array.size

15

In [27]:
random_array.shape

(3, 5)

In [30]:
# Return random floats in half open interval in an array
random_array2 = np.random.random((5, 3))
random_array2

array([[0.59699071, 0.36738532, 0.8455902 ],
       [0.45701831, 0.94643366, 0.78875994],
       [0.04118103, 0.97612289, 0.60400371],
       [0.02654964, 0.56462904, 0.02405562],
       [0.90919631, 0.60494372, 0.55328936]])

In [31]:
random_array2.shape

(5, 3)

In [32]:
# Return values in a given shape with random values
random_array3 = np.random.rand(5,3)
random_array3

array([[0.86261993, 0.07254861, 0.12691979],
       [0.02023675, 0.66605123, 0.97259375],
       [0.80727967, 0.71801742, 0.07378028],
       [0.27211597, 0.49448682, 0.94402553],
       [0.42039191, 0.28427645, 0.06428601]])

In [ ]:
# Pseudo-random numbers
np.random.seed()